#!/usr/bin/env bash
# Install nginx on my web server
sudo apt-get update -y
sudo apt-get upgrade -y
sudo apt-get install -y nginx
sudo chown -R "$USER":"$USER" /var/www/
sudo chown -R "$USER":"$USER" /etc/nginx
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo service nginx restart
