#!/usr/bin/env bash
#add a custom Nginx response header now.
sudo apt-get update -y
sudo apt-get upgrade -y
sudo apt-get install -y nginx
sudo chown -R "$USER":"$USER" /var/www/
sudo chown -R "$USER":"$USER" /etc/nginx
echo "Hello World!" > /var/www/html/index.nginx-debian.html
red="\\\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}"
sed -i "53i $red" /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" > /var/www/html/404.html
ero="\\\terror_page 404 /404.html;\n\tlocation = /404.html {\n\t\troot /var/www/html;\n\t\tinternal;\n\t}"
sed -i "47i $ero" /etc/nginx/sites-available/default
vari=$(hostname)
web1="server \{\n\tadd_header X-Served-By $vari;"
sudo sed -i -E "s/^server \{/$web1/" /etc/nginx/sites-available/default
sudo service nginx restart
