#!/usr/bin/env bash
# Manages the script manage_my_process.
#   When passed the argument `start`:
#     1. Starts manage_my_process
#     2. Creates a file containings its PID in /var/run/my_process.pid
#     3. Displays "manage_my_process started"
#
#   When passed the argument `stop`:
#     1. Stops manage_my_process
#     2. Deletes the file /var/run/my_process.pid
#     3. Displays "manage_my_process stopped"
#
#   When passed the argument `restart`:
#     1. Stops manage_my_process
#     2. Deletes the file /var/run/my_process.pid
#     3. Starts manage_my_process
#     4. Creates a file containing its PID in /var/run/my_process.pid
#     5. Displays "manage_my_process restarted"
#
#   If any other or no arguments are passed, displays
#+  "Usage: manage_my_process {start|stop|restart}"

FILE="/var/run/my_process.pid"

function error()
{
	echo "Usage: manage_my_process {start|stop|restart}"
}

function start()
{
	(./manage_my_process) &
	echo $$ > $FILE
	echo "manage_my_process started"
}

function stop()
{
	pkill -f ./manage_my_process
	sudo rm -f $FILE
	echo "manage_my_process stopped"
}

function restart()
{
	pkill -f ./manage_my_process
	sudo rm -f $FILE
	./manage_my_process &
	echo $$ > $FILE
	echo "manage_my_process restarted"
}

if [ $# -ne 1 ];
then
	error
else
	case ${1} in
		"start")
			start;;
		"restart")
			restart;;
		"stop")
			stop;;
		*)
			error;;
	esac
fi
