#!/usr/bin/env bash
# Displays:
#    To infinity and beyond 
#    With a sleep 2 in between 
#    I am invincible!!! when receiving a SIGTERM signal.

trap "echo I am invincible!!!" SIGTERM

while true
do
	echo "To infinity and beyond"
	sleep 2
done
