#!/usr/bin/env bash
#script nadu
counter=0
while [ $counter -le 20 ]
do
    if [ $counter == 4 ]
    then
        echo "4"
        echo "bad luck from China"
    elif [ $counter == 9 ]
    then
        echo "9"
        echo "bad luck from Japan"
    elif [ $counter == 17 ]
    then
        echo "17"
        echo "bad luck from Italy"
    else
        echo "$counter"
    fi
    ((counter++))
done
